# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional'] 
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  NUM_NODES = 2 # Up to 9 !

  1.upto(NUM_NODES) do |node_num|
    node_name = "rmq#{node_num}"
    config.vm.define node_name do |node|
      node.vm.hostname = "#{node_name}"
      node.vm.box = "centos-6.3"
      node.vm.network "private_network", ip: "192.168.33.10#{node_num}"
      node.vm.provision :shell, path: "install_rabbit_server.sh"
    end
  end
end
