export RABBITMQ_NODENAME="rmq1"
# export RABBITMQ_NODE_PORT=
# export RABBITMQ_SERVER_START_ARGS=
_RABBITMQ_INSTALL_DIR="/home/alext/Projects/rabbitmq-public-umbrella/rabbitmq-server"
_RABBITMQ_RUN_DIR="/home/alext/Run/${RABBITMQ_NODENAME}"
export RABBITMQ_HOME="$_RABBITMQ_INSTALL_DIR"
export RABBITMQ_CONFIG_FILE="$_RABBITMQ_RUN_DIR/${RABBITMQ_NODENAME}.config"
export RABBITMQ_ENABLED_PLUGINS_FILE="$_RABBITMQ_RUN_DIR/${RABBITMQ_NODENAME}.enabled_plugins"
export RABBITMQ_PLUGINS_DIR="${_RABBITMQ_INSTALL_DIR}/plugins/"
# export RABBITMQ_PLUGINS_DIR=
# export RABBITMQ_NODE_IP_ADDRESS=0.0.0.0 \
export RABBITMQ_LOG_BASE="${_RABBITMQ_RUN_DIR}/logs"
mkdir -p $RABBITMQ_LOG_BASE
